/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2p2_gerardodiaz12141095;

/**
 *
 * @author gerar
 */
public class MainUltimo extends javax.swing.JFrame {

    /**
     * Creates new form MainUltimo
     */
    public MainUltimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pg_hiloCancion = new javax.swing.JProgressBar();
        jl_cancion = new javax.swing.JLabel();
        scroll_tree = new javax.swing.JScrollPane();
        jt_cancion = new javax.swing.JTree();
        scroll_ta = new javax.swing.JScrollPane();
        ta_escribirCancion = new javax.swing.JTextArea();
        panel = new javax.swing.JPanel();
        jb_grabarCancion = new javax.swing.JButton();
        jb_guardarCancion = new javax.swing.JButton();
        jb_ReproduccionCancion = new javax.swing.JButton();
        jb_PausarCancion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pg_hiloCancion.setToolTipText("P");
        pg_hiloCancion.setString(Integer.toString(pg_hiloCancion.getValue())+" Minutos");
        pg_hiloCancion.setStringPainted(true);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Canciones");
        jt_cancion.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_cancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_cancionMouseClicked(evt);
            }
        });
        scroll_tree.setViewportView(jt_cancion);

        ta_escribirCancion.setColumns(20);
        ta_escribirCancion.setRows(5);
        scroll_ta.setViewportView(ta_escribirCancion);

        panel.setLayout(new java.awt.GridLayout(1, 0));

        jb_grabarCancion.setText("Grabar Cancion");
        jb_grabarCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_grabarCancionMouseClicked(evt);
            }
        });
        panel.add(jb_grabarCancion);

        jb_guardarCancion.setText("Guardar Cancion");
        jb_guardarCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarCancionMouseClicked(evt);
            }
        });
        panel.add(jb_guardarCancion);

        jb_ReproduccionCancion.setText("Reproduccion Cancion  ");
        jb_ReproduccionCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ReproduccionCancionMouseClicked(evt);
            }
        });
        panel.add(jb_ReproduccionCancion);

        jb_PausarCancion.setText("Pausar Cancion");
        jb_PausarCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_PausarCancionMouseClicked(evt);
            }
        });
        panel.add(jb_PausarCancion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scroll_tree, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                                    .addComponent(scroll_ta))))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addComponent(pg_hiloCancion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pg_hiloCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_tree)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scroll_ta, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_cancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_cancionMouseClicked
        // TODO add your handling code here:
        
        

    }//GEN-LAST:event_jt_cancionMouseClicked

    private void jb_grabarCancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_grabarCancionMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jb_grabarCancionMouseClicked

    private void jb_guardarCancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarCancionMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jb_guardarCancionMouseClicked

    private void jb_ReproduccionCancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ReproduccionCancionMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jb_ReproduccionCancionMouseClicked

    private void jb_PausarCancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_PausarCancionMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jb_PausarCancionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUltimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUltimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUltimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUltimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUltimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_PausarCancion;
    private javax.swing.JButton jb_ReproduccionCancion;
    private javax.swing.JButton jb_grabarCancion;
    private javax.swing.JButton jb_guardarCancion;
    private javax.swing.JLabel jl_cancion;
    private javax.swing.JTree jt_cancion;
    private javax.swing.JPanel panel;
    public javax.swing.JProgressBar pg_hiloCancion;
    private javax.swing.JScrollPane scroll_ta;
    private javax.swing.JScrollPane scroll_tree;
    private javax.swing.JTextArea ta_escribirCancion;
    // End of variables declaration//GEN-END:variables
}
